#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/algos
#
# IDENTIFICATION
#    src/backend/utils/algos/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/algos
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

override CPPFLAGS := -I. -I$(srcdir) $(CPPFLAGS)

OBJS = bin_search.o misc_tools.o

include $(top_srcdir)/src/backend/common.mk

