#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/heap
#
# IDENTIFICATION
#    src/backend/access/heap/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/remote
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = dml.o meta.o remote_xact.o

include $(top_srcdir)/src/backend/common.mk
