drop table if exists t1;
create table t1(a serial primary key, b int);
insert into t1(b) values(11),(22),(33);

alter table t1 add column c int not null;
\d+ t1;
select*from t1;
alter table t1 drop column c;
select*from t1;
alter table t1 add column c int;
\d+ t1;
select*from t1;



alter table t1 add column d varchar(32) not null;
alter table t1 add column d varchar(32);
\d+ t1;
select*, d is null as disnull, length(d) from t1;

alter table t1 alter column d set default 'ddd';
\d+ t1;
insert into t1(b) values(77);
select*from t1;
alter table t1 alter column d drop default;
\d+ t1;



create table t30(a serial primary key, b int unique not null default 3);
alter table t30 add column c serial unique;
insert into t30 (b) values(11),(12),(13);
insert into t30 (b) values(14);
insert into t30 (b) values(15);
insert into t30 (b) values(16);
insert into t30 (b) values(17);
select*from t30;

alter table t30 rename a to aa;
alter table t30 rename b to bb;
alter table t30 rename c to cc;

alter table t30 add column e int not null;
alter table t30 add column f int;
alter table t30 alter column bb drop default;
alter table t30 alter column bb add generated by default as identity(start 100);
\d+ t30;
insert into t30(e) values(1111),(1111),(1111),(1111);
update t30 set f=2222;
select*from t30;

alter table t30 alter column e add generated by default as identity, alter column f set not null, alter column f add generated by default as identity, alter bb drop identity;
\d+ t30;


drop table if exists t1;
drop table if exists t100;
drop table if exists t101;
drop table if exists t102;
drop table if exists t103;
drop table if exists t30;
drop table if exists t301;
drop table if exists t302;
drop table if exists t303;
drop table if exists t304;

create table t1(a serial primary key, b int) partition by hash(a);
create table t100 partition of t1 for values with (modulus 4, remainder 0);
create table t101 partition of t1 for values with (modulus 4, remainder 1);
create table t102 partition of t1 for values with (modulus 4, remainder 2);
create table t103 partition of t1 for values with (modulus 4, remainder 3);

insert into t1(b) values(11),(22),(33);

alter table t1 add column c int not null;

\d+ t1;
select*from t1;
alter table t1 drop column c;
select*from t1;

alter table t1 add column d varchar(32) not null;
alter table t1 add column d varchar(32);
\d+ t1;
select*, d is null as disnull, length(d) from t1;

alter table t1 alter column d set default 'ddd';
\d+ t1;
insert into t1(b) values(77);
select*from t1;
alter table t1 alter column d drop default;
\d+ t1;
insert into t1(b) values(77);
select*from t1;



create table t30(a serial , b int unique not null default 3, primary key(a,b)) partition by range(b);
create table t301 partition of t30 for values from (0) to (10000);
create table t302 partition of t30 for values from (10000) to (20000);
create table t303 partition of t30 for values from (20000) to (30000);
create table t304 partition of t30 for values from (30000) to (40000);

alter table t30 add column c serial;
insert into t30 (b) values(11),(12),(13),(14),(15);
insert into t30 (b) values(14000),(14001),(14002),(14003),(14004);
insert into t30 (b) values(25000),(25001),(25002),(25003),(25004);
insert into t30 (b) values(36000),(36001),(36002),(36003),(36004);
select*from t30;

alter table t30 add column d serial;
select*from t30;

alter table t30 rename a to aa;
alter table t30 rename b to bb;
alter table t30 rename c to cc;

alter table t30 add column e int not null;
alter table t30 add column f int;
alter table t30 alter column bb drop default, alter column bb add generated by default as identity(start 100);
\d+ t30;
insert into t30(e) values(1111),(1111),(1111),(1111);
update t30 set f=2222;
select*from t30;

alter table t30 alter column e add generated by default as identity, alter column f set not null, alter column f add generated by default as identity, alter bb drop identity;
\d+ t30;
insert into t30(bb) values(200),(201),(202),(203);
select*from t30;


