#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for sharding
#
# IDENTIFICATION
#    src/backend/sharding/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/sharding
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = mysql_vars.o sharding_conn.o cluster_meta.o

include $(top_srcdir)/src/backend/common.mk
