--
-- Test foreign-data wrapper and server management.
--

-- Clean up in case a prior regression run failed

-- Suppress NOTICE messages when roles don't exist
SET client_min_messages TO 'warning';

--DDL_STATEMENT_BEGIN--
DROP ROLE IF EXISTS regress_foreign_data_user, regress_test_role, regress_test_role2, regress_test_role_super, regress_test_indirect, regress_unprivileged_role;
--DDL_STATEMENT_END--

RESET client_min_messages;

--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_foreign_data_user LOGIN SUPERUSER;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET SESSION AUTHORIZATION 'regress_foreign_data_user';

--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_test_role2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_test_role_super SUPERUSER;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_test_indirect;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE ROLE regress_unprivileged_role;
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER dummy;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON FOREIGN DATA WRAPPER dummy IS 'useless';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER postgresql VALIDATOR postgresql_fdw_validator;
--DDL_STATEMENT_END--

-- At this point we should have 2 built-in wrappers and no servers.
SELECT fdwname, fdwhandler::regproc, fdwvalidator::regproc, fdwoptions FROM pg_foreign_data_wrapper ORDER BY 1, 2, 3;
SELECT srvname, srvoptions FROM pg_foreign_server;
--Its value changes frequently and is temporarily cancelled
--SELECT * FROM pg_user_mapping;

-- CREATE FOREIGN DATA WRAPPER
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo VALIDATOR bar;            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
\dew

--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo; -- duplicate
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo OPTIONS (testing '1');
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo OPTIONS (testing '1', testing '2');   -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo OPTIONS (testing '1', another '2');
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo; -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo VALIDATOR postgresql_fdw_validator;
--DDL_STATEMENT_END--
\dew+

-- HANDLER related checks
--DDL_STATEMENT_BEGIN--
CREATE FUNCTION invalid_fdw_handler() RETURNS int LANGUAGE SQL AS 'SELECT 1;';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER test_fdw HANDLER invalid_fdw_handler;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER test_fdw HANDLER test_fdw_handler HANDLER invalid_fdw_handler;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER test_fdw HANDLER test_fdw_handler;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER test_fdw;
--DDL_STATEMENT_END--

-- ALTER FOREIGN DATA WRAPPER
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo;                             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo VALIDATOR bar;               -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo NO VALIDATOR;
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (a '1', b '2');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (SET c '4');         -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (DROP c);            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (ADD x '1', DROP x);
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (DROP a, SET b '3', ADD c '4');
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (a '2');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (b '4');             -- ERROR
--DDL_STATEMENT_END--
\dew+

SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (ADD d '5');         -- ERROR
--DDL_STATEMENT_END--
SET ROLE regress_test_role_super;
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (ADD d '5');
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OWNER TO regress_test_role;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OWNER TO regress_test_role_super;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER ROLE regress_test_role_super NOSUPERUSER;
--DDL_STATEMENT_END--
SET ROLE regress_test_role_super;
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (ADD e '6');         -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
\dew+

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo RENAME TO foo1;
--DDL_STATEMENT_END--
\dew+
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo1 RENAME TO foo;
--DDL_STATEMENT_END--

-- HANDLER related checks
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo HANDLER invalid_fdw_handler;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo HANDLER test_fdw_handler HANDLER anything;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo HANDLER test_fdw_handler;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FUNCTION invalid_fdw_handler();
--DDL_STATEMENT_END--

-- DROP FOREIGN DATA WRAPPER
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER nonexistent;                      -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER IF EXISTS nonexistent;
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_role_super;                          -- ERROR
--DDL_STATEMENT_END--
SET ROLE regress_test_role_super;
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_role_super;
--DDL_STATEMENT_END--
\dew+

--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s1 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON SERVER s1 IS 'foreign server';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s1;				-- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING IF NOT EXISTS FOR current_user SERVER s1; -- NOTICE
--DDL_STATEMENT_END--
\dew+
\des+
\deu+
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;                              -- ERROR
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo CASCADE;                      -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo CASCADE;
--DDL_STATEMENT_END--
\dew+
\des+
\deu+

-- exercise CREATE SERVER
--DDL_STATEMENT_BEGIN--
CREATE SERVER s1 FOREIGN DATA WRAPPER foo;                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foo OPTIONS ("test wrapper" 'true');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s1 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s1 FOREIGN DATA WRAPPER foo;                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER IF NOT EXISTS s1 FOREIGN DATA WRAPPER foo;	-- No ERROR, just NOTICE
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s2 FOREIGN DATA WRAPPER foo OPTIONS (host 'a', dbname 'b');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s3 TYPE 'oracle' FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s4 TYPE 'oracle' FOREIGN DATA WRAPPER foo OPTIONS (host 'a', dbname 'b');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s5 VERSION '15.0' FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s6 VERSION '16.0' FOREIGN DATA WRAPPER foo OPTIONS (host 'a', dbname 'b');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s7 TYPE 'oracle' VERSION '17.0' FOREIGN DATA WRAPPER foo OPTIONS (host 'a', dbname 'b');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s8 FOREIGN DATA WRAPPER postgresql OPTIONS (foo '1'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s8 FOREIGN DATA WRAPPER postgresql OPTIONS (host 'localhost', dbname 's8db');
--DDL_STATEMENT_END--
\des+
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE SERVER t1 FOREIGN DATA WRAPPER foo;                 -- ERROR: no usage on FDW
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_role;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE SERVER t1 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
RESET ROLE;
\des+

--DDL_STATEMENT_BEGIN--
REVOKE USAGE ON FOREIGN DATA WRAPPER foo FROM regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_indirect;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE SERVER t2 FOREIGN DATA WRAPPER foo;                 -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
GRANT regress_test_indirect TO regress_test_role;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE SERVER t2 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
\des+
RESET ROLE;
--DDL_STATEMENT_BEGIN--
REVOKE regress_test_indirect FROM regress_test_role;
--DDL_STATEMENT_END--

-- ALTER SERVER
--DDL_STATEMENT_BEGIN--
ALTER SERVER s0;                                            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s0 OPTIONS (a '1');                            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 VERSION '1.0' OPTIONS (servername 's1');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s2 VERSION '1.1';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s3 OPTIONS ("tns name" 'orcl', port '1521');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s1 TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s6 TO regress_test_role2 WITH GRANT OPTION;
--DDL_STATEMENT_END--
\des+
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 VERSION '1.1';                              -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_role;                 -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT regress_test_role2 TO regress_test_role;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 VERSION '1.1';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_role2;                -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s8 OPTIONS (foo '1');                          -- ERROR option validation
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s8 OPTIONS (connect_timeout '30', SET dbname 'db1', DROP host);
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_indirect;             -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
GRANT regress_test_indirect TO regress_test_role;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_indirect;
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_indirect;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
ALTER SERVER s1 OWNER TO regress_test_indirect;
--DDL_STATEMENT_END--
RESET ROLE;
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_indirect;                            -- ERROR
--DDL_STATEMENT_END--
\des+

--DDL_STATEMENT_BEGIN--
ALTER SERVER s8 RENAME to s8new;
--DDL_STATEMENT_END--
\des+
--DDL_STATEMENT_BEGIN--
ALTER SERVER s8new RENAME to s8;
--DDL_STATEMENT_END--

-- DROP SERVER
--DDL_STATEMENT_BEGIN--
DROP SERVER nonexistent;                                    -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER IF EXISTS nonexistent;
--DDL_STATEMENT_END--
\des
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
DROP SERVER s2;                                             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s1;
--DDL_STATEMENT_END--
RESET ROLE;
\des
--DDL_STATEMENT_BEGIN--
ALTER SERVER s2 OWNER TO regress_test_role;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
DROP SERVER s2;
--DDL_STATEMENT_END--
RESET ROLE;
\des
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s3;
--DDL_STATEMENT_END--
\deu
--DDL_STATEMENT_BEGIN--
DROP SERVER s3;                                             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s3 CASCADE;
--DDL_STATEMENT_END--
\des
\deu

-- CREATE USER MAPPING
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR regress_test_missing_role SERVER s1;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s1;             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR user SERVER s4;                     -- ERROR duplicate
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s4 OPTIONS ("this mapping" 'is public');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR user SERVER s8 OPTIONS (username 'test', password 'secret');    -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR user SERVER s8 OPTIONS (user 'test', password 'secret');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s5 OWNER TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s6 OWNER TO regress_test_indirect;
--DDL_STATEMENT_END--
SET ROLE regress_test_role;
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s5;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s6 OPTIONS (username 'test');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s7;             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s8;                   -- ERROR
--DDL_STATEMENT_END--
RESET ROLE;

--DDL_STATEMENT_BEGIN--
ALTER SERVER t1 OWNER TO regress_test_indirect;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER t1 OPTIONS (username 'bob', password 'boo');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER t1;
--DDL_STATEMENT_END--
RESET ROLE;
\deu

-- ALTER USER MAPPING
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR regress_test_missing_role SERVER s4 OPTIONS (gotcha 'true'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR user SERVER ss4 OPTIONS (gotcha 'true'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR public SERVER s5 OPTIONS (gotcha 'true');            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR current_user SERVER s8 OPTIONS (username 'test');    -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR current_user SERVER s8 OPTIONS (DROP user, SET password 'public');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR current_user SERVER s5 OPTIONS (ADD modified '1');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR public SERVER s4 OPTIONS (ADD modified '1'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR public SERVER t1 OPTIONS (ADD modified '1');
--DDL_STATEMENT_END--
RESET ROLE;
\deu+

-- DROP USER MAPPING
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR regress_test_missing_role SERVER s4;  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR user SERVER ss4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR public SERVER s7;                     -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING IF EXISTS FOR regress_test_missing_role SERVER s4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING IF EXISTS FOR user SERVER ss4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING IF EXISTS FOR public SERVER s7;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s8;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR public SERVER s8;                     -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
RESET ROLE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s7;
--DDL_STATEMENT_END--
\deu

-- CREATE FOREIGN TABLE
--DDL_STATEMENT_BEGIN--
CREATE SCHEMA foreign_schema;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s0 FOREIGN DATA WRAPPER dummy;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 ();                                    -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 () SERVER no_server;                   -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 () SERVER s0;                -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 (
	c1 integer OPTIONS ("param 1" 'val1') PRIMARY KEY,
	c2 text OPTIONS (param2 'val2', param3 'val3'),
	c3 date
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE TABLE ref_table (id integer PRIMARY KEY);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 (
	c1 integer OPTIONS ("param 1" 'val1'),
	c2 text OPTIONS (param2 'val2', param3 'val3'),
	c3 date
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP TABLE ref_table;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 (
	c1 integer OPTIONS ("param 1" 'val1') NOT NULL,
	c2 text OPTIONS (param2 'val2', param3 'val3'),
	c3 date,
	UNIQUE (c3)
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft1 (
	c1 integer OPTIONS ("param 1" 'val1') NOT NULL,
	c2 text OPTIONS (param2 'val2', param3 'val3'),
	c3 date
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON FOREIGN TABLE ft1 IS 'ft1';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON COLUMN ft1.c1 IS 'ft1.c1';
--DDL_STATEMENT_END--
\d+ ft1
\det+
--DDL_STATEMENT_BEGIN--
CREATE INDEX id_ft1_c2 ON ft1 (c2);                             -- ERROR
--DDL_STATEMENT_END--
SELECT * FROM ft1;                                              -- ERROR
EXPLAIN SELECT * FROM ft1;                                      -- ERROR

--DDL_STATEMENT_BEGIN--
CREATE TABLE lt1 (a INT) PARTITION BY RANGE (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part1
  PARTITION OF lt1 FOR VALUES FROM (0) TO (1000) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE INDEX ON lt1 (a);                              -- skips partition
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE UNIQUE INDEX ON lt1 (a);                                 -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE lt1 ADD PRIMARY KEY (a);                            -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP TABLE lt1;
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
CREATE TABLE lt1 (a INT) PARTITION BY RANGE (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE INDEX ON lt1 (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part1
  PARTITION OF lt1 FOR VALUES FROM (0) TO (1000) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part2 PARTITION OF lt1 FOR VALUES FROM (1000) TO (2000) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE ft_part1, ft_part2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE UNIQUE INDEX ON lt1 (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE lt1 ADD PRIMARY KEY (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part1 PARTITION OF lt1 FOR VALUES FROM (0) TO (1000) SERVER s0;     -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part2 PARTITION OF lt1 FOR VALUES FROM (1000) TO (2000) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP TABLE lt1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE ft_part2;
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
CREATE TABLE lt1 (a INT) PARTITION BY RANGE (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE INDEX ON lt1 (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE TABLE lt1_part1
  PARTITION OF lt1 FOR VALUES FROM (0) TO (1000)
  PARTITION BY RANGE (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part_1_1
  PARTITION OF lt1_part1 FOR VALUES FROM (0) TO (100) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part_1_2 PARTITION OF lt1_part1 FOR VALUES FROM (100) TO (200) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE UNIQUE INDEX ON lt1 (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE lt1 ADD PRIMARY KEY (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE ft_part_1_1, ft_part_1_2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE UNIQUE INDEX ON lt1 (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE lt1 ADD PRIMARY KEY (a);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part_1_1
  PARTITION OF lt1_part1 FOR VALUES FROM (0) TO (100) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft_part_1_2 PARTITION OF lt1_part1 FOR VALUES FROM (100) TO (200) SERVER s0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP TABLE lt1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE ft_part_1_2;
--DDL_STATEMENT_END--

-- ALTER FOREIGN TABLE
--DDL_STATEMENT_BEGIN--
COMMENT ON FOREIGN TABLE ft1 IS 'foreign table';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON FOREIGN TABLE ft1 IS NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON COLUMN ft1.c1 IS 'foreign column';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
COMMENT ON COLUMN ft1.c1 IS NULL;
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c4 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c5 integer DEFAULT 0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c6 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c7 integer NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c8 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c9 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD COLUMN c10 integer OPTIONS (p1 'v1');
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c4 SET DEFAULT 0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c5 DROP DEFAULT;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c6 SET NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c7 DROP NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c8 TYPE char(10) USING '0'; -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c8 TYPE char(10);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c8 SET DATA TYPE text;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN xmin OPTIONS (ADD p1 'v1'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c7 OPTIONS (ADD p1 'v1', ADD p2 'v2'),
                        ALTER COLUMN c8 OPTIONS (ADD p1 'v1', ADD p2 'v2');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--						
ALTER FOREIGN TABLE ft1 ALTER COLUMN c8 OPTIONS (SET p2 'V2', DROP p1);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c1 SET (n_distinct = 100);
--DDL_STATEMENT_END--
\d+ ft1
-- can't change the column type if it's used elsewhere
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ALTER COLUMN c8 SET DATA TYPE integer;	-- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 ADD PRIMARY KEY (c7);                   -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 DROP CONSTRAINT no_const;               -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 DROP CONSTRAINT IF EXISTS no_const;
--DDL_STATEMENT_END--
--ALTER FOREIGN TABLE ft1 SET WITH OIDS;
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 OWNER TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
--ALTER FOREIGN TABLE ft1 OPTIONS (DROP delimiter, SET quote '~', ADD escape '@');
ALTER FOREIGN TABLE ft1 DROP COLUMN no_column;                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 DROP COLUMN IF EXISTS no_column;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 DROP COLUMN c9;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 SET SCHEMA foreign_schema;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE ft1 SET TABLESPACE ts;                      -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE foreign_schema.ft1 RENAME c1 TO foreign_column_1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE foreign_schema.ft1 RENAME TO foreign_table_1;
--DDL_STATEMENT_END--
\d foreign_schema.foreign_table_1

-- alter noexisting table
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c4 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c6 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c7 integer NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c8 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c9 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ADD COLUMN c10 integer OPTIONS (p1 'v1');
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c6 SET NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c7 DROP NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c8 TYPE char(10);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c8 SET DATA TYPE text;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c7 OPTIONS (ADD p1 'v1', ADD p2 'v2'),
                        ALTER COLUMN c8 OPTIONS (ADD p1 'v1', ADD p2 'v2');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--						
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 ALTER COLUMN c8 OPTIONS (SET p2 'V2', DROP p1);
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 DROP CONSTRAINT IF EXISTS no_const;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 OWNER TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 OPTIONS (DROP delimiter, SET quote '~', ADD escape '@');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 DROP COLUMN IF EXISTS no_column;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 DROP COLUMN c9;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 SET SCHEMA foreign_schema;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 RENAME c1 TO foreign_column_1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN TABLE IF EXISTS doesnt_exist_ft1 RENAME TO foreign_table_1;
--DDL_STATEMENT_END--

-- Information schema

SELECT * FROM information_schema.foreign_data_wrappers ORDER BY 1, 2;
SELECT * FROM information_schema.foreign_data_wrapper_options ORDER BY 1, 2, 3;
SELECT * FROM information_schema.foreign_servers ORDER BY 1, 2;
SELECT * FROM information_schema.foreign_server_options ORDER BY 1, 2, 3;
SELECT * FROM information_schema.user_mappings ORDER BY lower(authorization_identifier), 2, 3;
SELECT * FROM information_schema.user_mapping_options ORDER BY lower(authorization_identifier), 2, 3, 4;
SELECT * FROM information_schema.usage_privileges WHERE object_type LIKE 'FOREIGN%' AND object_name IN ('s6', 'foo') ORDER BY 1, 2, 3, 4, 5;
SELECT * FROM information_schema.role_usage_grants WHERE object_type LIKE 'FOREIGN%' AND object_name IN ('s6', 'foo') ORDER BY 1, 2, 3, 4, 5;
SELECT * FROM information_schema.foreign_tables ORDER BY 1, 2, 3;
SELECT * FROM information_schema.foreign_table_options ORDER BY 1, 2, 3, 4;
SET ROLE regress_test_role;
SELECT * FROM information_schema.user_mapping_options ORDER BY 1, 2, 3, 4;
SELECT * FROM information_schema.usage_privileges WHERE object_type LIKE 'FOREIGN%' AND object_name IN ('s6', 'foo') ORDER BY 1, 2, 3, 4, 5;
SELECT * FROM information_schema.role_usage_grants WHERE object_type LIKE 'FOREIGN%' AND object_name IN ('s6', 'foo') ORDER BY 1, 2, 3, 4, 5;
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR current_user SERVER t1;
--DDL_STATEMENT_END--
SET ROLE regress_test_role2;
SELECT * FROM information_schema.user_mapping_options ORDER BY 1, 2, 3, 4;
RESET ROLE;


-- has_foreign_data_wrapper_privilege
SELECT has_foreign_data_wrapper_privilege('regress_test_role',
    (SELECT oid FROM pg_foreign_data_wrapper WHERE fdwname='foo'), 'USAGE');
SELECT has_foreign_data_wrapper_privilege('regress_test_role', 'foo', 'USAGE');
SELECT has_foreign_data_wrapper_privilege(
    (SELECT oid FROM pg_roles WHERE rolname='regress_test_role'),
    (SELECT oid FROM pg_foreign_data_wrapper WHERE fdwname='foo'), 'USAGE');
SELECT has_foreign_data_wrapper_privilege(
    (SELECT oid FROM pg_foreign_data_wrapper WHERE fdwname='foo'), 'USAGE');
SELECT has_foreign_data_wrapper_privilege(
    (SELECT oid FROM pg_roles WHERE rolname='regress_test_role'), 'foo', 'USAGE');
SELECT has_foreign_data_wrapper_privilege('foo', 'USAGE');
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_role;
--DDL_STATEMENT_END--
SELECT has_foreign_data_wrapper_privilege('regress_test_role', 'foo', 'USAGE');

-- has_server_privilege
SELECT has_server_privilege('regress_test_role',
    (SELECT oid FROM pg_foreign_server WHERE srvname='s8'), 'USAGE');
SELECT has_server_privilege('regress_test_role', 's8', 'USAGE');
SELECT has_server_privilege(
    (SELECT oid FROM pg_roles WHERE rolname='regress_test_role'),
    (SELECT oid FROM pg_foreign_server WHERE srvname='s8'), 'USAGE');
SELECT has_server_privilege(
    (SELECT oid FROM pg_foreign_server WHERE srvname='s8'), 'USAGE');
SELECT has_server_privilege(
    (SELECT oid FROM pg_roles WHERE rolname='regress_test_role'), 's8', 'USAGE');
SELECT has_server_privilege('s8', 'USAGE');
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s8 TO regress_test_role;
--DDL_STATEMENT_END--
SELECT has_server_privilege('regress_test_role', 's8', 'USAGE');
--DDL_STATEMENT_BEGIN--
REVOKE USAGE ON FOREIGN SERVER s8 FROM regress_test_role;
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s4 TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR public SERVER s4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s6 OPTIONS (DROP host, DROP dbname);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR regress_test_role SERVER s6 OPTIONS (DROP username);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo VALIDATOR postgresql_fdw_validator;
--DDL_STATEMENT_END--

-- Privileges
SET ROLE regress_unprivileged_role;
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foobar;                             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (gotcha 'true');         -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OWNER TO regress_unprivileged_role; -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;                                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_role;   -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s9 FOREIGN DATA WRAPPER foo;                      -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s4 VERSION '0.5';                                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s4 OWNER TO regress_unprivileged_role;             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s4;                                                 -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s4 TO regress_test_role;          -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s4;                       -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR regress_test_role SERVER s6 OPTIONS (gotcha 'true'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR regress_test_role SERVER s6;              -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
RESET ROLE;

--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER postgresql TO regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_unprivileged_role WITH GRANT OPTION;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN DATA WRAPPER foobar;                             -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER FOREIGN DATA WRAPPER foo OPTIONS (gotcha 'true');         -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo;                                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER postgresql TO regress_test_role; -- WARNING
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s9 FOREIGN DATA WRAPPER postgresql;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s6 VERSION '0.5';                                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s6;                                                 -- ERROR
--DDL_STATEMENT_END--
--DDL_STAx                                                                        TEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s6 TO regress_test_role;          -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s9 TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s6;                       -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s9;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER USER MAPPING FOR regress_test_role SERVER s6 OPTIONS (gotcha 'true'); -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR regress_test_role SERVER s6;              -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
RESET ROLE;

--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
REVOKE USAGE ON FOREIGN DATA WRAPPER foo FROM regress_unprivileged_role; -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
REVOKE USAGE ON FOREIGN DATA WRAPPER foo FROM regress_unprivileged_role CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN DATA WRAPPER foo TO regress_test_role;   -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s10 FOREIGN DATA WRAPPER foo;                     -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s9 VERSION '1.1';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s9 TO regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s9;
--DDL_STATEMENT_END--
-- We use terse mode to avoid ordering issues in cascade detail output.
--DDL_STATEMENT_BEGIN--
\set VERBOSITY terse
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s9 CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY default
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
RESET ROLE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s9 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s9 TO regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
SET ROLE regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER SERVER s9 VERSION '1.2';                                  -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
GRANT USAGE ON FOREIGN SERVER s9 TO regress_test_role;          -- WARNING
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR current_user SERVER s9;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s9 CASCADE;                                         -- ERROR

--DDL_STATEMENT_END--
-- Check visibility of user mapping data
--DDL_STATEMENT_BEGIN--
SET ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE SERVER s10 FOREIGN DATA WRAPPER foo;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR public SERVER s10 OPTIONS (user 'secret');
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE USER MAPPING FOR regress_unprivileged_role SERVER s10 OPTIONS (user 'secret');
--DDL_STATEMENT_END--
-- owner of server can see some option fields
\deu+
RESET ROLE;
-- superuser can see all option fields
\deu+
-- unprivileged user cannot see any option field
SET ROLE regress_unprivileged_role;
\deu+
--DDL_STATEMENT_BEGIN--
RESET ROLE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY terse
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s10 CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY default

--DDL_STATEMENT_END--
-- Table inheritance
--DDL_STATEMENT_BEGIN--
CREATE TABLE fd_pt1 (
	c1 integer NOT NULL,
	c2 text,
	c3 date
);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft2 (
	c1 integer NOT NULL,
	c2 text,
	c3 date
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value');
--DDL_STATEMENT_END--


-- add attributes recursively
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ADD COLUMN c4 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ADD COLUMN c5 integer DEFAULT 0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ADD COLUMN c6 integer;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ADD COLUMN c7 integer NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ADD COLUMN c8 integer;
--DDL_STATEMENT_END--
\d+ fd_pt1
\d+ ft2
\d+ ct3
\d+ ft3

-- alter attributes recursively
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c4 SET DEFAULT 0;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c5 DROP DEFAULT;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c6 SET NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c7 DROP NOT NULL;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c8 TYPE char(10) USING '0';
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c8 TYPE char(10);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c8 SET DATA TYPE text;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 ALTER COLUMN c1 SET (n_distinct = 100);
--DDL_STATEMENT_END--
\d+ fd_pt1
\d+ ft2

-- drop attributes recursively
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 DROP COLUMN c4;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 DROP COLUMN c5;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 DROP COLUMN c6;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 DROP COLUMN c7;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 DROP COLUMN c8;
--DDL_STATEMENT_END--
\d+ fd_pt1
\d+ ft2

-- add constraints recursively
SELECT relname, conname, contype, conislocal, coninhcount, connoinherit
  FROM pg_class AS pc JOIN pg_constraint AS pgc ON (conrelid = pc.oid)
  WHERE pc.relname = 'fd_pt1'
  ORDER BY 1,2;
\d+ fd_pt1
\d+ ft2
--DDL_STATEMENT_BEGIN--
\set VERBOSITY terse
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE ft2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY default
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE ft2 (
	c1 integer NOT NULL,
	c2 text,
	c3 date
) SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value');
--DDL_STATEMENT_END--
\d+ fd_pt1
\d+ ft2

-- NOT VALID case
INSERT INTO fd_pt1 VALUES (1, 'fd_pt1'::text, '1994-01-01'::date);
\d+ fd_pt1
\d+ ft2


-- changes name of an attribute recursively
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 RENAME COLUMN c1 TO f1;
--DDL_STATEMENT_END-- 
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 RENAME COLUMN c2 TO f2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt1 RENAME COLUMN c3 TO f3;
--DDL_STATEMENT_END--
-- changes name of a constraint recursively
\d+ fd_pt1
\d+ ft2

--DDL_STATEMENT_BEGIN--
DROP TABLE fd_pt1 CASCADE;
--DDL_STATEMENT_END--

-- IMPORT FOREIGN SCHEMA
IMPORT FOREIGN SCHEMA s1 FROM SERVER s9 INTO public; -- ERROR
IMPORT FOREIGN SCHEMA s1 LIMIT TO (t1) FROM SERVER s9 INTO public; --ERROR
IMPORT FOREIGN SCHEMA s1 EXCEPT (t1) FROM SERVER s9 INTO public; -- ERROR
IMPORT FOREIGN SCHEMA s1 EXCEPT (t1, t2) FROM SERVER s9 INTO public
OPTIONS (option1 'value1', option2 'value2'); -- ERROR

-- DROP FOREIGN TABLE@
--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE no_table;                                    -- ERROR
--DDL_STATEMENT_END--

--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE IF EXISTS no_table;
--DDL_STATEMENT_END--
-- REASSIGN OWNED/DROP OWNED of foreign objects
REASSIGN OWNED BY regress_test_role TO regress_test_role2;

-- Foreign partition DDL stuff
--DDL_STATEMENT_BEGIN--
CREATE TABLE fd_pt2 (
	c1 integer NOT NULL,
	c2 text,
	c3 date
) PARTITION BY LIST (c1);
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
CREATE FOREIGN TABLE fd_pt2_1 PARTITION OF fd_pt2 FOR VALUES IN (1)
  SERVER s0 OPTIONS (delimiter ',', quote '"', "be quoted" 'value');
--DDL_STATEMENT_END--
\d+ fd_pt2
\d+ fd_pt2_1

-- cannot add column to a partition
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt2_1 ADD c4 char;
--DDL_STATEMENT_END--
-- ok to have a partition's own constraints though
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt2_1 ALTER c3 SET NOT NULL;
--DDL_STATEMENT_END--
\d+ fd_pt2
\d+ fd_pt2_1

-- cannot drop inherited NOT NULL constraint from a partition
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt2_1 ALTER c1 DROP NOT NULL;
--DDL_STATEMENT_END--

-- partition must have parent's constraints
--DDL_STATEMENT_BEGIN--
ALTER TABLE fd_pt2 ALTER c2 SET NOT NULL;
--DDL_STATEMENT_END--
\d+ fd_pt2
\d+ fd_pt2_1

--DDL_STATEMENT_BEGIN--
DROP FOREIGN TABLE fd_pt2_1;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP TABLE fd_pt2;
--DDL_STATEMENT_END--

-- Cleanup
--DDL_STATEMENT_BEGIN--
DROP SCHEMA foreign_schema CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_role;                                -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER t1 CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP USER MAPPING FOR regress_test_role SERVER s6;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY terse
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER foo CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP SERVER s8 CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
\set VERBOSITY default
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_indirect;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_unprivileged_role;                        -- ERROR
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
REVOKE ALL ON FOREIGN DATA WRAPPER postgresql FROM regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_unprivileged_role;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_test_role2;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER postgresql CASCADE;
--DDL_STATEMENT_END--
--DDL_STATEMENT_BEGIN--
DROP FOREIGN DATA WRAPPER dummy CASCADE;
--DDL_STATEMENT_END--
\c
--DDL_STATEMENT_BEGIN--
DROP ROLE regress_foreign_data_user;
--DDL_STATEMENT_END--

-- At this point we should have no wrappers, no servers, and no mappings.
SELECT fdwname, fdwhandler, fdwvalidator, fdwoptions FROM pg_foreign_data_wrapper;
SELECT srvname, srvoptions FROM pg_foreign_server;\
--Its value changes frequently and is temporarily cancelled
--SELECT * FROM pg_user_mapping;
